---
title: "proj_2015"
author: "Andrew Martin"
date: "July 11, 2015"
output: html_document
---


libraries etc
```{r lib}
library(dplyr)
library(zoo)
```

load the data from previous analysis

```{r data_prep, message=FALSE, error=FALSE, warning=FALSE, include=FALSE}
knitr::knit('stat_avg.Rmd', tangle=TRUE)
source('stat_avg.R')

```

use windowing to get rolling n-day averages

```{r windows}

hpk_munge <- hpk_all %>%
  dplyr::filter(!is.na(value)) %>%
  group_by(year, stat_id, team_key) %>%
  arrange(year, team_key, stat_id, date) %>%
  mutate(
    rolling_3 = zoo::rollmean(x = as.numeric(value), k = 3, align = "right", na.pad = TRUE),
    rolling_5 = zoo::rollmean(x = as.numeric(value), k = 5, align = "right", na.pad = TRUE),
    rolling_7 = zoo::rollmean(x = as.numeric(value), k = 7, align = "right", na.pad = TRUE),
    rolling_10 = zoo::rollmean(x = as.numeric(value), k = 10, align = "right", na.pad = TRUE),  
    rolling_15 = zoo::rollmean(x = as.numeric(value), k = 15, align = "right", na.pad = TRUE),
    rolling_20 = zoo::rollmean(x = as.numeric(value), k = 20, align = "right", na.pad = TRUE),    
    rolling_25 = zoo::rollmean(x = as.numeric(value), k = 25, align = "right", na.pad = TRUE),    
    rolling_30 = zoo::rollmean(x = as.numeric(value), k = 30, align = "right", na.pad = TRUE),
    rolling_35 = zoo::rollmean(x = as.numeric(value), k = 35, align = "right", na.pad = TRUE),    
    rolling_40 = zoo::rollmean(x = as.numeric(value), k = 40, align = "right", na.pad = TRUE),    
    rolling_45 = zoo::rollmean(x = as.numeric(value), k = 45, align = "right", na.pad = TRUE),
    rolling_50 = zoo::rollmean(x = as.numeric(value), k = 50, align = "right", na.pad = TRUE)    
  )

```


```{r ex_chart}

ggplot(
  data = hpk_munge %>% dplyr::filter(stat_name == 'TB' & year == 2015 & team_key %in% c('346.l.49099.t.8', '346.l.49099.t.3')),
  aes(
    x = date,
    group = team_key,
    color = team_key,
    size = team_key
  )
) +
geom_line(
  aes(y = rolling_7),
  color = 'red'
) +  
geom_line(
  aes(y = rolling_15),
  color = 'orange'
) +  
geom_line(
  aes(y = rolling_20),
  color = 'blue'
) +  
theme_bw()

```



```{r ex_chart}

ggplot(
  data = hpk_munge %>% dplyr::filter(stat_name == 'TB' & year == 2015 ),
  aes(
    x = date,
    y = rolling_10,
    group = team_key,
    color = team_key
  )
) + 
geom_line(
  smooth = 2
) +
theme_bw()

```
